# Generated by Django 3.1.2 on 2020-10-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizevariation',
            options={'verbose_name_plural': 'Litre Sizes'},
        ),
    ]
