# Generated by Django 3.1.2 on 2020-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201027_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
